name: Check

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
